# Generated by Django 5.2.15 on 2026-06-11 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Über mich')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('study_program', models.CharField(blank=True, max_length=100, verbose_name='Studiengang')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/', verbose_name='Foto')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Geburtstag')),
                ('interests', models.CharField(blank=True, max_length=255, verbose_name='Interessen')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Einwilligung erteilt')),
                ('consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Einwilligungsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
