# Generated by Django 5.2.15 on 2026-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_is_beta_tester_feedbackentry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/', verbose_name='Profilfoto'),
        ),
    ]
